// Generated by CoffeeScript 1.3.3

this.onmessage = function(event) {
  var a, b, bv, dataRef, g, gv, imageData, index, parsed, r, rv, t, val, xpos, ypos, _i, _j, _ref, _ref1;
  imageData = event.data.imageData;
  parsed = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(event.data.colorConstant);
  rv = parseInt(parsed[1], 16);
  gv = parseInt(parsed[2], 16);
  bv = parseInt(parsed[3], 16);
  val = rv + gv + bv;
  t = event.data.rgbTolerance;
  for (xpos = _i = 0, _ref = imageData.width - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; xpos = 0 <= _ref ? ++_i : --_i) {
    for (ypos = _j = 0, _ref1 = imageData.height - 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; ypos = 0 <= _ref1 ? ++_j : --_j) {
      index = 4 * (ypos * imageData.width + xpos);
      dataRef = imageData.data;
      r = dataRef[index];
      g = dataRef[index + 1];
      b = dataRef[index + 2];
      a = dataRef[index + 3];
      if (t !== void 0) {
        if (r <= rv + t.r && g <= gv + t.g && b <= bv + t.b) {
          dataRef[index + 3] = 0;
        }
      } else if ((r + g + b) === val) {
        dataRef[index + 3] = 0;
      }
    }
  }
  return this.postMessage(imageData);
};
